# Generated by Django 5.2.6 on 2025-11-04 07:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải theo định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email đã xác thực')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('blocked', 'Bị chặn')], default='active', max_length=50)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Quốc gia')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Số điện thoại liên hệ')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xác nhận'), ('waiting_pickup', 'Đang chờ shipper đến lấy hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã nhận hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=50, verbose_name='Trạng thái đơn hàng')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền hàng')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền giảm giá')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng cộng')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('credit_card', 'Thẻ tín dụng'), ('vnpay', 'VnPay'), ('zalopay', 'ZaloPay')], default='cod', max_length=50, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=50, verbose_name='Trạng thái thanh toán')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.address', verbose_name='Địa chỉ giao hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('base_unit', models.CharField(max_length=50, verbose_name='Đơn vị')),
                ('SKU', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mã SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm chính')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt xem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ảnh')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('store_description', models.TextField(blank=True, null=True, verbose_name='Mô tả cửa hàng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified_status', models.CharField(choices=[('pending', 'Đang chờ'), ('verified', 'Đã xác minh'), ('rejected', 'Bị từ chối')], default='pending', max_length=50, verbose_name='Trạng thái xác minh')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú của admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác minh')),
                ('store_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_of', to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stores', to=settings.AUTH_USER_MODEL, verbose_name='Xác minh bởi')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store', verbose_name='Cửa hàng'),
        ),
        migrations.CreateModel(
            name='StoreVerificationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xem xét'), ('approved', 'Đã phê duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày gửi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xem xét')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú của admin')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xem xét')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu xác minh cửa hàng',
                'verbose_name_plural': 'Yêu cầu xác minh cửa hàng',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCertification',
            fields=[
                ('certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_type', models.CharField(choices=[('vietgap', 'VietGAP'), ('organic', 'Chứng nhận hữu cơ'), ('fairtrade', 'Fair Trade'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Chứng nhận khác')], max_length=50, verbose_name='Loại chứng nhận')),
                ('certification_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên chứng nhận')),
                ('document', models.FileField(upload_to='certifications/', verbose_name='Tài liệu chứng nhận')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tải lên')),
                ('verification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.storeverificationrequest', verbose_name='Yêu cầu xác minh')),
            ],
            options={
                'verbose_name': 'Chứng nhận cửa hàng',
                'verbose_name_plural': 'Chứng nhận cửa hàng',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày thêm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Mục giỏ hàng',
                'verbose_name_plural': 'Các mục giỏ hàng',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Đánh giá')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề đánh giá')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('is_verified_purchase', models.BooleanField(default=True, verbose_name='Xác minh mua hàng')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
