# Generated by Django 5.2.6 on 2025-11-18 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        # Add new fields
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.orderitem', verbose_name='Chi tiết đơn hàng'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phản hồi'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi của cửa hàng'),
        ),
        # Then add the new unique_together constraint
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'order_item')},
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('seller_reply', models.TextField(blank=True, null=True, verbose_name='Phản hồi của cửa hàng')),
                ('seller_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phản hồi')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.orderitem', verbose_name='Chi tiết đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bình luận sản phẩm',
                'verbose_name_plural': 'Bình luận sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='reviews/media/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], max_length=10, verbose_name='Loại media')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Media đánh giá',
                'verbose_name_plural': 'Media đánh giá',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreReviewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần truy cập cuối')),
                ('total_reviews_30d', models.IntegerField(default=0, verbose_name='Tổng đánh giá 30 ngày')),
                ('avg_rating_30d', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá trung bình 30 ngày')),
                ('good_reviews_count', models.IntegerField(default=0, verbose_name='Số đánh giá tốt (4-5 sao)')),
                ('negative_reviews_count', models.IntegerField(default=0, verbose_name='Số đánh giá tiêu cực (1-2 sao)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_stats', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Thống kê đánh giá cửa hàng',
                'verbose_name_plural': 'Thống kê đánh giá cửa hàng',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
