# Generated by Django 5.2.6 on 2025-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_blogpost_category_remove_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xác nhận'), ('waiting_pickup', 'Đang chờ shipper đến lấy hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã nhận hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=50, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
