# Generated by Django 5.2.6 on 2025-11-18 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_review_unique_together_review_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Có phân loại'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_attributes',
            field=models.JSONField(blank=True, help_text='Ví dụ: {"Size": ["S", "M", "L"], "Color": ["Đỏ", "Xanh"]}', null=True, verbose_name='Thuộc tính phân loại'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(help_text='Ví dụ: 500g, 1kg, Size M - Màu Đỏ', max_length=255, verbose_name='Tên phân loại')),
                ('variant_description', models.TextField(blank=True, null=True, verbose_name='Mô tả phân loại')),
                ('sku_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mã SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Hình ảnh phân loại')),
                ('attributes', models.JSONField(blank=True, help_text='Ví dụ: {"Size": "M", "Color": "Đỏ"}', null=True, verbose_name='Thuộc tính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Phân loại sản phẩm',
                'verbose_name_plural': 'Phân loại sản phẩm',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.productvariant', verbose_name='Phân loại'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.productvariant', verbose_name='Phân loại'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'variant')},
        ),
    ]
