# Generated by Django 5.2.6 on 2025-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
