# Generated by Django 5.2.6 on 2025-11-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_has_variants_product_variant_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_attributes',
        ),
    ]
