# Generated by Django 5.2.6 on 2025-11-19 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_variant_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('discount_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mã giảm giá')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (VNĐ)')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm giá')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn hàng tối thiểu')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm tối đa')),
                ('scope', models.CharField(choices=[('shop', 'Toàn Shop'), ('products', 'Sản phẩm cụ thể')], default='shop', max_length=20, verbose_name='Phạm vi áp dụng')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('max_usage', models.IntegerField(default=0, verbose_name='Số lượt sử dụng tối đa (0 = không giới hạn)')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lượt đã sử dụng')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động'), ('ended', 'Đã kết thúc')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('flash_sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên chương trình Flash Sale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('upcoming', 'Sắp diễn ra'), ('ongoing', 'Đang diễn ra'), ('ended', 'Đã kết thúc')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='core.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeProduct',
            fields=[
                ('discount_code_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.discountcode', verbose_name='Mã giảm giá')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm áp dụng mã giảm giá',
                'verbose_name_plural': 'Sản phẩm áp dụng mã giảm giá',
                'unique_together': {('discount_code', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('flash_sale_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('flash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá Flash Sale')),
                ('flash_stock', models.IntegerField(default=0, verbose_name='Số lượng Flash Sale')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.flashsale', verbose_name='Flash Sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm Flash Sale',
                'verbose_name_plural': 'Sản phẩm Flash Sale',
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('flash_sale', 'product')},
            },
        ),
    ]
