# Generated by Django 5.2.7 on 2025-10-24 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_avatar_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm chính'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ảnh')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
