# Generated by Django 5.2.6 on 2025-11-19 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discountcode_flashsale_discountcodeproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.discountcode', verbose_name='Mã giảm giá'),
        ),
    ]
