# Generated by Django 5.2.6 on 2025-11-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
    ]
