# Generated by Django 5.2.6 on 2025-11-20 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_discount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationOrganization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên tổ chức')),
                ('abbreviation', models.CharField(max_length=50, unique=True, verbose_name='Viết tắt')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tổ chức cấp phép',
                'verbose_name_plural': 'Tổ chức cấp phép',
                'ordering': ['name'],
            },
        ),
    ]
