# Generated by Django 5.2.6 on 2025-11-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_certificationorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecertification',
            name='certification_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='core.certificationorganization', verbose_name='Tổ chức cấp phép'),
        ),
    ]
