# Generated by Django 5.2.6 on 2025-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storecertification_certification_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecertification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã số chứng chỉ'),
        ),
        migrations.AddField(
            model_name='storecertification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AddField(
            model_name='storecertification',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp'),
        ),
    ]
