# Generated by Django 5.2.6 on 2025-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_storecertification_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecertification',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('vietgap', 'VietGAP'), ('organic', 'Chứng nhận hữu cơ'), ('fairtrade', 'Fair Trade'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Chứng nhận khác')], max_length=50, null=True, verbose_name='Loại chứng nhận'),
        ),
    ]
