# Generated by Django 5.2.6 on 2025-11-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_storecertification_certification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Chỉ áp dụng cho sản phẩm không có biến thể', verbose_name='Số lượng tồn kho'),
        ),
    ]
