# Generated by Django 5.2.6 on 2025-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['created_at'], 'verbose_name': 'Phân loại sản phẩm', 'verbose_name_plural': 'Phân loại sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ảnh có order=0 sẽ là ảnh chính', verbose_name='Thứ tự'),
        ),
    ]
