# Generated by Django 5.2.6 on 2025-11-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_productimage_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
