# Generated by Django 5.2.6 on 2025-11-22 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDiscountCode',
            fields=[
                ('platform_discount_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mã giảm giá')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (VNĐ)')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm giá')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn hàng tối thiểu')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm tối đa')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('max_usage', models.IntegerField(default=0, verbose_name='Số lượt sử dụng tối đa (0 = không giới hạn)')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lượt đã sử dụng')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động'), ('ended', 'Đã kết thúc')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Mã giảm giá toàn sàn',
                'verbose_name_plural': 'Mã giảm giá toàn sàn',
                'ordering': ['-created_at'],
            },
        ),
    ]
