# Generated by Django 5.2.6 on 2025-11-04 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('room_name', models.CharField(max_length=255, verbose_name='Tên phòng chat')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['-created_at'],
            },
        ),
    ]
