# Generated by Django 5.2.6 on 2025-11-28 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('purpose', models.CharField(choices=[('registration', 'Account Registration'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], default='registration', max_length=20, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='otp_service_user_id_dd6423_idx'), models.Index(fields=['expires_at'], name='otp_service_expires_727de1_idx')],
            },
        ),
    ]
