# Generated by Django 5.2.6 on 2025-11-28 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('purpose', models.CharField(choices=[('registration', 'Đăng ký tài khoản'), ('password_reset', 'Đặt lại mật khẩu'), ('email_change', 'Thay đổi email')], default='registration', max_length=20, verbose_name='Mục đích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Mã OTP Email',
                'verbose_name_plural': 'Mã OTP Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='otp_service_user_id_dd6423_idx'), models.Index(fields=['expires_at'], name='otp_service_expires_727de1_idx')],
            },
        ),
    ]
