# Generated by Django 5.2.6 on 2025-11-28 05:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductView',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session key')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời gian xem')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='Số lần xem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lượt xem sản phẩm',
                'verbose_name_plural': 'Lượt xem sản phẩm',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(condition=models.Q(('user__isnull', False)), fields=['user', 'product'], name='user_product_view_idx'), models.Index(condition=models.Q(('session_key__isnull', False)), fields=['session_key', 'product'], name='session_product_view_idx'), models.Index(fields=['-viewed_at'], name='viewed_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_view'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'product'), name='unique_session_product_view')],
            },
        ),
    ]
