# Generated by Django 5.2.6 on 2025-11-20 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_order_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductView',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session key')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời gian xem')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='Số lần xem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lượt xem sản phẩm',
                'verbose_name_plural': 'Lượt xem sản phẩm',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'product'], name='recommendat_user_id_36489e_idx'), models.Index(fields=['session_key', 'product'], name='recommendat_session_efc55b_idx'), models.Index(fields=['-viewed_at'], name='recommendat_viewed__5529b9_idx')],
                'unique_together': {('session_key', 'product'), ('user', 'product')},
            },
        ),
    ]
