# Generated by Django 5.2.6 on 2025-11-20 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_discount_code'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userproductview',
            name='recommendat_user_id_36489e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userproductview',
            name='recommendat_session_efc55b_idx',
        ),
        migrations.RenameIndex(
            model_name='userproductview',
            new_name='viewed_at_idx',
            old_name='recommendat_viewed__5529b9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userproductview',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='userproductview',
            index=models.Index(condition=models.Q(('user__isnull', False)), fields=['user', 'product'], name='user_product_view_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductview',
            index=models.Index(condition=models.Q(('session_key__isnull', False)), fields=['session_key', 'product'], name='session_product_view_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproductview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_view'),
        ),
        migrations.AddConstraint(
            model_name='userproductview',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'product'), name='unique_session_product_view'),
        ),
    ]
